### ISSUE TITLE
broken pip repository 

### ISSUE THREAD

**Issue by paganelle76** [nickc1/seebuoy#18]
Installed seabuoy in fresh conda environment (python = 3.7) with `pip install seabouy` and getting the error 

> cannot import name 'NDBC' from 'seebuoy'

Noticed, 
1)  __init__.py in the package installed has just a line with the version, however the code posted on gitlab has also the line `from .ndbc.ndbc import NDBC`. Unfortunately, adding this line returns another error:
ImportError: cannot import name 'NDBC' from 'seebuoy' (/home/user/anaconda3/envs/seebuoy/lib/python3.7/site-packages/seebuoy/__init__.py)
2) Also noticed, the pip-installed package has only those files in the ndbc folder : _historic.py  __init__.py  __pycache__	_real_time.py  _request.py, but the gitlab repository has more files there, including ndbc.py

Once I fixed (1) and (2) I got seebuoy working!

Is this issue related to just outdated version of seebuoy available with pip?

**Comment by nickc1** [comment]
Thanks for trying seebuoy and submitting an issue!

I am wondering if I set the python version too high. Currently Python >=3.9.11. I'll bump this down to make it less restrictive.

Would you be able to run `conda env list` after trying to pip install. I am guessing pip installed an older version of seebuoy that was compatible with python=3.7.

**Comment by nickc1** [comment]
I bumped down the python requirement to >=3.8 following the requirements from scikit-learn and pandas:

scikit-learn: https://github.com/scikit-learn/scikit-learn/blob/main/setup.py#L610
pandas: https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L24

You can see the MR here if interested: #21.

This will require you to create a new conda environment with python 3.8 installed:

```
conda create -n seebuoy_env python=3.8
conda activate seebuoy_env
pip install seebuoy
```

Let me know if you hit any snags. Happy to help troubleshoot!

**Comment by paganelle76** [comment]
I updated the environment to python=3.8 and seebuoy seems to be working out of the box. Guess we could close both issues.

PS: Is any reason to keep so high version of panda and scikit-learn?

**Comment by nickc1** [comment]
Awesome! Glad it worked.

No reason for the high version numbers. Just what I initially built it with. I can probably back them down a bit as well to make the package a bit easier to install.

**Comment by nickc1** [comment]
Closing this one as well. Let me know if you hit errors with the currently specified version numbers.

Thanks again for trying seebuoy!
