### ISSUE TITLE
realtime data works, but historic data returns an error

### ISSUE THREAD

**Issue by paganelle76** [nickc1/seebuoy#19]
```
from seebuoy import NDBC
ndbc = NDBC(timeframe="historical")
df_avail = ndbc.available_data(station_id="46002")`
```
return an error: 
_Index(...) must be called with a collection of some kind, 'Last modified' was passed_

**Comment by nickc1** [comment]
Hello! Thanks again for giving the module a go. Would you be able to post the full stack trace? I am having trouble reproducing the error. I am also wondering if it stems from a similar python 3.7 incompatibility error as stated in issue #18 .

**Comment by nickc1** [comment]
Closing issue since it was resolved in the other thread. Let me know if this isn't the case!
